version: '3.8'
services:
  app:
    build: .

    depends_on:
      - db

    ports:
      - 8000:8000

  db:
    image: postgres:11
    environment:
     - POSTGRES_DB=facebook
     - POSTGRES_USER=facebook_admin
     - POSTGRES_PASSWORD=password
