# Generated by Django 4.2.7 on 2023-12-02 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255)),
                ('post_link', models.CharField(max_length=255)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('reaction_count', models.IntegerField()),
                ('reaction_type', models.JSONField()),
                ('comment_count', models.IntegerField()),
            ],
        ),
    ]
