# Generated by Django 4.2.7 on 2023-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='publish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='reaction_type',
            field=models.JSONField(null=True),
        ),
    ]
